export interface JobSearchResult {
  nPostingJobId: number;
  sJobTilte: string;
  sLocation: string;
  sCity: string;
  sState: string;
  isJobRemote: number;
  nEmploymentType?: null;
  nIndustryId?: null;
  sSalaryRangeMin: number;
  sJobDescription: string;
  sWorkExperianceMin?: null;
  nEducationId?: null;
  nPreferredMajor?: null;
  nPreferredGpa?: null;
  nNotiEmailId?: null;
  bNeedToTravel?: null;
  sLanguage: string;
  sCustomRequirement: string;
  sSalaryRangeMax: number;
  sWorkExperianceAnyRelevant: number;
  snBackgroundCheck: number;
  snExprPreferredReq: number;
  snEduPreferredReq: number;
  bActive: number;
  bDelete: number;
  dtCreatedDate?: null;
  dtEditedDate?: null;
  dtDeletedDate?: null;
  nCreatedBy?: null;
  nEditedBy?: null;
  nDeletedBy?: null;
  jobType: string;
  ncursor: number;
  inferredCountry: string;
  country: string;
  crawlTimestamp?: null;
  inferredCity: string;
  salaryOffered: string;
  url: string;
  geo: string;
  uniqId?: null;
  inferredState: string;
  jobBoard: string;
  postDate: string;
  companyName: string;
  category: string;
  contactEmail: string;
  contactPhoneNumber: string;
  htmlJobDescription: string;
  validThrough: string;
  hasExpired: boolean;
  inferredIso3LangCode: string;
  latestExpiryCheckDate: string;
  duplicateStatus: string;
  duplicateOf: string;
  inferredDepartmentName: string;
  inferredDepartmentScore: number;
  inferredJobTitle: string;
  inferredSalaryCurrency: string;
  inferredSalaryTimeUnit: string;
  inferredCompanyType: string;
  inferredCompanyTypeScore: number;
  inferredSeniorityLevel: string;
  applyUrl: string;
  applyJob?: (null)[] | null;
  jobSkill?: (JobSkillEntity)[] | null;
  saveJob?: (null)[] | null;
}
export interface JobSkillEntity {
  nInferredSkillId: number;
  nPostJobId: number;
  sSkill: string;
  nPostJob?: null;
}
